name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Run integration tests
        run: cd java-security-it; mvn -B package --file pom.xml
      - name: Build spring-security-basic-auth
        run: cd samples/spring-security-basic-auth; mvn -B package --file pom.xml
      - name: Build spring-security-xsuaa-usage
        run: cd samples/spring-security-xsuaa-usage; mvn -B package --file pom.xml
      - name: Build spring-webflux-security-xsuaa-usage
        run: cd samples/spring-webflux-security-xsuaa-usage; mvn -B package --file pom.xml
      - name: Build java-security-usage
        run: cd samples/java-security-usage; mvn -B package --file pom.xml
      - name: Build sap-java-buildpack-api-usage
        run: cd samples/sap-java-buildpack-api-usage; mvn -B package --file pom.xml
      - name: Build java-tokenclient-usage
        run: cd samples/java-tokenclient-usage; mvn -B package --file pom.xml
      - name: Push SpotBugs report
        # You may pin to the exact commit or the version.
        # uses: jwgmeligmeyling/spotbugs-github-action@b8e2c3523acb34c87f14e18cbcd2d87db8c8584e
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          # A file, directory or wildcard pattern that describes where to find the reports
          path: '**/findbugsXml.xml'
